import fs from "node:fs";
import path from "node:path";
import type { AnalysisResult, Fix } from "./analyze.js";

function imageToDataUrl(filePath: string): string {
  const data = fs.readFileSync(filePath).toString("base64");
  const ext = filePath.toLowerCase().split(".").pop();
  const mime = ext === "jpg" || ext === "jpeg" ? "image/jpeg" : "image/png";
  return `data:${mime};base64,${data}`;
}

function severityBadge(severity: string): string {
  const colors: Record<string, string> = {
    OK: "#22c55e",
    MINOR: "#eab308",
    MAJOR: "#ef4444",
  };
  const color = colors[severity] || "#6b7280";
  return `<span style="background:${color};color:#000;padding:4px 12px;border-radius:4px;font-weight:bold;">${severity}</span>`;
}

export function generateReport(
  url: string,
  referencePath: string,
  capturedPath: string,
  diffPath: string,
  diffPercent: number,
  analysis: AnalysisResult,
  fixes: Fix[],
  outputDir: string,
): string {
  const timestamp = new Date().toISOString();
  const refDataUrl = imageToDataUrl(referencePath);
  const capDataUrl = imageToDataUrl(capturedPath);
  const diffDataUrl = imageToDataUrl(diffPath);

  const issuesHtml = analysis.issues
    .map(
      (issue) => `
      <div style="background:#1e1e2e;padding:12px 16px;border-radius:6px;margin-bottom:8px;">
        <strong style="color:#cdd6f4;">#${issue.id} ${issue.title}</strong>
        <span style="color:#6c7086;margin-left:12px;">${issue.area}</span>
        <p style="color:#a6adc8;margin:6px 0 0;">${issue.description}</p>
      </div>`,
    )
    .join("\n");

  let fixesHtml: string;
  if (fixes.length === 0) {
    fixesHtml = `<p style="color:#6c7086;font-style:italic;">No fixes requested.</p>`;
  } else {
    fixesHtml = fixes
      .map(
        (fix) => `
      <div style="background:#1e1e2e;padding:12px 16px;border-radius:6px;margin-bottom:8px;">
        <strong style="color:#cdd6f4;">[${fix.id}] ${fix.title}</strong>
        <pre style="color:#a6e3a1;margin:8px 0 0;white-space:pre-wrap;font-size:13px;">${fix.suggestion}</pre>
      </div>`,
      )
      .join("\n");
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Visual Mirror Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #11111b;
      color: #cdd6f4;
      font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
      padding: 32px;
      line-height: 1.6;
    }
    h1 { color: #cba6f7; font-size: 24px; margin-bottom: 8px; }
    h2 { color: #89b4fa; font-size: 18px; margin: 32px 0 16px; }
    .header-meta {
      color: #6c7086;
      font-size: 13px;
      margin-bottom: 24px;
    }
    .header-meta span { margin-right: 24px; }
    .image-grid {
      display: grid;
      grid-template-columns: 1fr 1fr 1fr;
      gap: 16px;
      margin-bottom: 32px;
    }
    .image-grid div {
      text-align: center;
    }
    .image-grid img {
      width: 100%;
      border: 1px solid #313244;
      border-radius: 6px;
    }
    .image-grid p {
      color: #6c7086;
      font-size: 12px;
      margin-top: 8px;
    }
  </style>
</head>
<body>
  <h1>Visual Mirror Report</h1>
  <div class="header-meta">
    <span>URL: ${url}</span>
    <span>Time: ${timestamp}</span>
    <span>Diff: ${diffPercent.toFixed(1)}%</span>
    <span>${severityBadge(analysis.severity)}</span>
  </div>

  <h2>Screenshots</h2>
  <div class="image-grid">
    <div>
      <img src="${refDataUrl}" alt="Reference">
      <p>Reference</p>
    </div>
    <div>
      <img src="${capDataUrl}" alt="Captured">
      <p>Captured</p>
    </div>
    <div>
      <img src="${diffDataUrl}" alt="Diff">
      <p>Diff</p>
    </div>
  </div>

  <h2>Issues (${analysis.issues.length})</h2>
  ${issuesHtml || '<p style="color:#a6e3a1;">No issues detected.</p>'}

  <h2>Fix Suggestions</h2>
  ${fixesHtml}

  <p style="color:#45475a;margin-top:48px;font-size:11px;">Generated by visual-mirror</p>
</body>
</html>`;

  const reportPath = path.join(outputDir, "index.html");
  fs.writeFileSync(reportPath, html, "utf-8");
  return reportPath;
}
